#!/bin/sh

#Define Paths
pathRoot=`dirname $0`/../
pathBin=$pathRoot'etc/'
pathOut=$pathRoot'out/'
pathLegacy=$pathOut'legacy/'
pathEtui=$pathOut'etui/'

#Define binaries
binLessc=$pathBin'lessc'

addParams=''

#Constants
DEFAULT_ENTRY=etui

source=$DEFAULT_ENTRY

if [ $# -ge 1 ]
then
    source='/'$1
fi

if [ $# -ge 2 ]
then
    if [ "$2"="-x" ]
    then
        addParams=" $2"
    fi
fi

target=$pathOut$source

#Build salespage css

echo Source:        $source
echo Source Path:   `dirname $source`'/'
echo Target:        $target
echo Additions:     $addParams

if [ -d `dirname $target` ]
then
    echo releasing directory found
    # TODO optionally recreate directory --clean
else
    echo creating releasing directory
    # create parent directory also
    mkdir -p `dirname $target`
fi

echo building css
node $binLessc$addParams `dirname $0`$source.less > $target'.css'
echo building rtl css
node $binLessc$addParams `dirname $0`$source.rtl.less > $target'.rtl.css'
